### PR TITLE
[WIP] Add setup.py

### PR DESCRIPTION
**Pull request by Yard1**
This PR intends to prepare the contents of LA-MCTS folder for distribution.

Only the `lamcts` folder will be included in the package itself.

### CODE REVIEW

**Comment by Yard1** [comment]
@linnanwang Would it be possible for you to look over the setup.py parameters (author, description, email)?

**Comment by linnanwang** [comment]
@Yard1 , thank you for your effort, this is great. I will take a look ASAP. Thank you.

**Comment by Yard1** [comment]
ATM only the `lamcts` folder will be included in the package itself. I think the `tracker` class could be moved there for convenience. One further improvement would be to create some sort of a generic wrapper around a function to optimize that would create a class which can be passed to `MCTS`, in order to simplify things. If you think that sounds like a good idea, I can look into it.

**Review by linnanwang — APPROVED** [review]
It looks good to me

**Pull request merged**
